[pytest]
minversion = 8.0
addopts = -ra -v
testpaths = tests
python_files = test_*.py

markers =
    smoke: Smoke-тесты - быстрая проверка работоспособности
    regression: Регрессионные тесты - полная проверка функциональности
